=== MichielMertens/OU_JP_MM_EVB/jabberpoint.dtd
<!-- Document Type Definition voor JabberPoint presentatties $Id$ -->
<!ELEMENT presentation (head,slide+)>
<!ELEMENT head (title)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT slide (title, items)>
<!ELEMENT items (text|image|action)*>
<!ELEMENT text (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT action (text|image|action)+>
<!ELEMENT slidenumber (#PCDATA)>
<!ATTLIST text level CDATA #REQUIRED>
<!ATTLIST image level CDATA #REQUIRED>
<!ATTLIST action name CDATA #REQUIRED>
<!ATTLIST action value CDATA #REQUIRED>

=== MichielMertens/OU_JP_MM_EVB/test_evb.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
	<head>
		<title>Demo Presentation for Jabberpoint</title>
	</head>
	<slide>
		<title>Title Slide</title>
		<items>
			<text level="1">Level 1 - TextItem</text>
			<text level="2">Level 2 - TextItem</text>
			<action name="next" value="">
				<action name="beep" value="">
					<action name="previous" value="">
						<!--<action name="goto" value="2"> -->
						<!--<action name="open" value="test.xml"> -->
						<text level="2">Next Page and beep</text>
						<!--</action> -->
						<!--</action> -->
					</action>
				</action>
			</action>
			<text level="2">Level 2 - last TextItem</text>
		</items>
	</slide>
</presentation>
